{% set name = "MiniAn" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/63/1f/ede8a5190ef92a0ab265cbc3f3480e60011761b9a92662c22013f7d9aa84/MiniAn-0.3.1.tar.gz
  sha256: 69ec6be7f4bef19df54f47e3e721afa696e6ecc78b2611f8a03cb28d044a9bda

build:
  number: 3
  script: "{{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . "
  entry_points:
    - minian-install = minian.install:main

requirements:
  host:
    - python ==3.8.1
    - pip
    - setuptools

  run:
    - bokeh =1.4.0
    - bottleneck =1.3.2
    - cairo =1.16.0
    - cvxpy =1.1.11
    - dask =2021.2.0
    - datashader =0.12.1
    - distributed =2021.2.0
    - ecos =2.0.7
    - ffmpeg =4.1.3
    - ffmpeg-python =0.2.0
    - fftw =3.3.8
    - holoviews =1.12.7
    - ipython =7.12.0
    - ipywidgets =7.5.1
    - jupyter =1.0.0
    - matplotlib =3.1.3
    - natsort =7.0.1
    - netcdf4 =1.5.3
    - networkx =2.4
    - nodejs =13.9.0
    - numba =0.52.0
    - numpy =1.20.2
    - opencv =4.2.0
    - pandas =1.2.3
    - panel =0.8.0
    - papermill =2.0.0
    - param =1.9.3
    - pyfftw =0.12.0
    - pytest-cov =2.9.0
    - python =3.8.1
    - scikit-image =0.18.1
    - scikit-learn =0.22.1
    - scipy =1.4.1
    - scs =2.1.1.2
    - sk-video =1.1.10
    - sparse =0.11.2
    - statsmodels =0.11.1
    - tifffile =2020.2.16
    - tqdm =4.43.0
    - xarray =0.17.0
    - zarr =2.4.0
    - pymetis=2020.1
    - rechunker=0.3.3

test:
  commands:
    - minian-install --demo --notebooks

about:
  home: https://github.com/DeniseCaiLab/minian
  summary: miniscope analysis pipeline with interactive visualizations
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://minian.readthedocs.io
  description: |
    MiniAn is an analysis pipeline and visualization tool inspired by both
    CaImAn and MIN1PIPE package specifically for Miniscope data.

extra:
  recipe-maintainers:
    - zsinnema
    - phildong
