{% set name = "MiniAn" %}
{% set version = "1.0.0rc0.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/46/a1/b33e93634d4151ac3a3ccd4571e24c0b4ee96ad59be1beb4df1b9311d327/minian-{{ version }}.tar.gz
  sha256: c87a520c478e3ff4a8eea68fa4ca6d5d9b1087b22f4cafe9dfb868b016332def

build:
  number: 0
  script: "{{ PYTHON }} -m pip install -vv --no-deps . "
  entry_points:
    - minian-install = minian.install:main

requirements:
  host:
    - python 3.8.*
    - pip
    - setuptools

  run:
    - bokeh =1.4.0
    - cvxpy >=1.1.11
    - dask =2021.2.0
    - datashader =0.12.1
    - distributed =2021.2.0
    - ecos >=2.0.7
    - ffmpeg
    - ffmpeg-python >=0.2.0
    - fftw
    - holoviews =1.12.7
    - jupyter
    - matplotlib-base
    - natsort
    - netcdf4
    - networkx =2.4
    - numba =0.52.0
    - numpy =1.20.2
    - opencv =4.2.0
    - pandas =1.2.3
    - panel =0.8.0
    - pyfftw >=0.12.0
    - python 3.8.*
    - pip
    - scikit-image =0.18.1
    - scikit-learn =0.22.1
    - scipy >=1.4.1
    - scs
    - sk-video
    - sparse =0.11.2
    - statsmodels >=0.11.1
    - tifffile
    - xarray =0.17.0
    - zarr
    - pymetis =2020.1
    - rechunker =0.3.3
    - simpleitk =2.0.2
test:
  commands:
    - minian-install --demo --notebooks

about:
  home: https://github.com/DeniseCaiLab/minian
  summary: miniscope analysis pipeline with interactive visualizations
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://minian.readthedocs.io
  description: |
    MiniAn is an analysis pipeline and visualization tool inspired by both
    CaImAn and MIN1PIPE package specifically for Miniscope data.

extra:
  recipe-maintainers:
    - zsinnema
    - phildong
